# Generated by Django 5.2.1 on 2025-06-08 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_dailytask_goal_dailytracker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dailytask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dailytracker',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='dailytracker',
            unique_together={('date', 'user')},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='dailytracker',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytracker',
            name='pending_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytracker',
            name='productivity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('career', 'Career'), ('health', 'Health'), ('education', 'Education'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointedJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('reflection', 'Reflection'), ('idea', 'Idea'), ('quote', 'Quote'), ('memory', 'Memory'), ('other', 'Other')], default='reflection', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='journal.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('tired', 'Tired'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='dailytracker',
            name='exercise_minutes',
        ),
        migrations.RemoveField(
            model_name='dailytracker',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='dailytracker',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='dailytracker',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dailytracker',
            name='water_intake',
        ),
    ]
