# Generated by Django 5.2.1 on 2025-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_tag_alter_dailytask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vent',
            name='key_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vent',
            name='sentiment_category',
            field=models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('very_negative', 'Very Negative')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='vent',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vent',
            name='subjectivity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
