# Generated by Django 5.2.1 on 2025-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_vent_key_phrases_vent_sentiment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vent',
            name='mood',
        ),
        migrations.AddField(
            model_name='vent',
            name='detected_mood',
            field=models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('anxiety', 'Anxiety'), ('calm', 'Calm'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
    ]
