# Generated by Django 5.2.1 on 2025-06-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('anxiety_score', models.FloatField(default=0.0)),
                ('self_hate_score', models.FloatField(default=0.0)),
                ('overall_sentiment', models.FloatField(default=0.0)),
                ('trigger_words', models.JSONField(default=list)),
                ('suggested_exercises', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'ordering': ['-entry_date'],
            },
        ),
    ]
